# Generated by Django 4.1.7 on 2023-02-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_barcode', models.CharField(max_length=120)),
                ('item_name', models.CharField(max_length=120)),
            ],
        ),
    ]
